### ISSUE TITLE
[EPIC] - Add Notify Me of Update Button

### ISSUE THREAD

**Issue by rbaker26** [rbaker26/SAP1EMU#118]
**Description:**
As a user, I want to be able to subscribe to updates about the site, so that I know when new features are released.

**To-Do List**
- [ ] Add a floating Button to the bottom right corner of the screen
- [ ] Create a form to allow users to subscribe to updates
- [ ] Create a email template to contain the updates
  - [ ] GDPR Compliance / Unsubscribe Feature 
- [ ] Entity Framework Core Models / Contexts Updates
- [ ] Azure MS SQL Server Updates
- [ ] Azure SMTP Email Server
- [ ] OWASP Data Security Checks
- [ ] Admin Portal for Sending Update Emails

**Definition of Done**
A user can subscribe and receive emails regarding updates.

**Screenshots (optional)**
