### ISSUE TITLE
[EPIC] - Ticket Portal GitHub API in WebApp

### ISSUE THREAD

**Issue by rbaker26** [rbaker26/SAP1EMU#119]
**Description:**
As a user, I want to be able to submit a bug report or feature request without using GitHub, so that I can easily give feedback without having access to developer tools.

**To-Do List**
- [ ] Build a Portal in the WebApp to allow users to submit bug reports
- [ ] Build a Portal in the WebApp to allow users to submit feature requests
- [ ] Integrate this portal with the GitHub API

**Definition of Done**
When a user can submit a bug report or a feature request to GitHub without logging into GitHub from the WebApp.

**Screenshots (optional)**
