### ISSUE TITLE
Update Contributing Documents

### ISSUE THREAD

**Issue by rbaker26** [rbaker26/SAP1EMU#120]
**Description:**
Update Repo Docs to assist new developers who want to help with the project.

**To-Do List**
- [ ] Update Contributing.md on Rules and Guidelines for Contribution 
- [ ] Create a Getting Started Guide
  - [ ] Getting Started in Windows
  - [ ] Getting Started in Linux
  - [ ] Getting Started in macOS.
- [ ] Update other Repo Level Project Docs

**Definition of Done**
A new Dev should be able to read the docs, build the project locally, make an update, and create a Pull Request.

**Screenshots (optional)**
