### ISSUE TITLE
SAP2 Planning Meeting Ticket

### ISSUE THREAD

**Issue by rbaker26** [rbaker26/SAP1EMU#146]
**Description:**
Need to make a plan for implementing the SAP2.

**To-Do List**
- [ ] How to handle User Input
- [ ] Return all Frames?
- [ ] How to handle Variable TStates
- [ ] Better ControlWord Interface
- [ ] GUI Layouts

**Definition of Done**
When we have a solid plan on how to build the SAP2

**Screenshots (optional)**
