### ISSUE TITLE
Ignoring Comments and Whitespace in GUI Editor Line Numbers

### ISSUE THREAD

**Issue by rbaker26** [rbaker26/SAP1EMU#85]
**What part of the project is your feature request for?**
 - [ ] Assembler CLI
 - [ ] Emulator CLI
 - [x] Emulator GUI
 - [ ] API  / Library

**Is your feature request related to a problem? Please describe.**

When a comment or newline is above a syntax error, it will throw-off the the number of the error message.
![image](https://user-images.githubusercontent.com/31376573/93963716-ca178880-fd12-11ea-8889-436657c8c8f9.png)

**Todo List**
- [ ] Line number should start at 0
- [ ] A blank line should not increment the line number
- [ ] A line containing only comments should not increment the line number

This will have to deal with the JavaScript passed to the CodeMirror Lib.
