### ISSUE TITLE
Save User Input to Database

### ISSUE THREAD

**Issue by rbaker26** [rbaker26/SAP1EMU#91]
**Description:**
It would be cool to save the user input into the emulator so we can analyze how people are using the site. 

**To-Do List**

- [x] Id best type of DB to user (MSSQL, MongoDB, CosmosDB, etc)
- [x] EF Core ~~or Store Procs~~?
- [ ] ~~Set up roles / auth for API and set trust levels~~
- [x] Azure holds the encrypted connection strings
