### ISSUE TITLE
Docs for API Integration for Student in College

### ISSUE THREAD

**Issue by rbaker26** [rbaker26/SAP1EMU#92]
**Description:**
The Docs/API section of this project needs to link to the Swagger/OpenAPI Docs and needs to run through how to connect to this API using common languages.

**To-Do List**
- [x] Swagger / OpenAPI Auto Docs
- [x] Swagger / OpenAPI JSON File
- [ ] Tutorials on how to use API
- [ ] Connecting with C# / .NET Core API Docs
- [ ] Connecting with Java API Docs
- [ ] Connecting with Python API Docs
- [ ] Connecting with Rust API Docs

**Definition of Done**
1. Passes all Integration Tests
2. Code can be handed off to a student and they are able to use the docs to create their API Client in their given language. 

**Screenshots (optional)**
An example of Swagger Auto Docs
![image](https://user-images.githubusercontent.com/31376573/94383836-fdcd2680-00f5-11eb-8cd9-058afd0aa087.png)
